database:
  provider: "mongodb"
  uri: "mongodb+srv://glitch:dattebayo@testcluster1.lccmg.mongodb.net/coordino?retryWrites=true&w=majority&appName=TestCluster1"
  database: "ai_interviewer"
  sessions_collection: "interview_sessions"
  metadata_collection: "interview_metadata"
  store_collection: "interview_memory_store"
  users_collection: "users"
  password_reset_tokens_collection: "password_reset_tokens"
  options:
    serverSelectionTimeoutMS: 30000
    socketTimeoutMS: 45000
    connectTimeoutMS: 30000 