database:
  provider: "mongodb"
  uri: "${MONGODB_URI}"
  database: "${MONGODB_DATABASE}"
  sessions_collection: "${MONGODB_SESSIONS_COLLECTION}"
  metadata_collection: "${MONGODB_METADATA_COLLECTION}"
  store_collection: "interview_memory_store"
  users_collection: "users"
  password_reset_tokens_collection: "password_reset_tokens"
  options:
    serverSelectionTimeoutMS: 30000
    socketTimeoutMS: 45000
    connectTimeoutMS: 30000 